/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistemadeinformacion;

import com.placeholder.PlaceHolder;
import java.io.BufferedReader;
import java.io.DataInputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.InputStreamReader;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.*;

/**
 *
 * @author Adan
 */
public class InterfazDocente extends javax.swing.JFrame {

    PlaceHolder miHolder;
    Connection miConexion;
    /**
     * Creates new form InterfazDocente
     */
    public InterfazDocente(String nombre,String apellidos,String usuarioo) {
        eti_bienvenidaD = new javax.swing.JLabel();
        initComponents();
        this.setLocationRelativeTo(null);
        eti_bienvenidaD.setText(nombre+" "+apellidos);
        usuarioDocente=usuarioo;
        mostrarMaterias();
        
        /*try
        {
            DefaultTableModel modelo=new DefaultTableModel();
            tablaCursos.setModel(modelo);
            
            PreparedStatement ps=null;
            ResultSet rs=null;
            miConexion=DriverManager.getConnection("jdbc:mysql://localhost:3306/proyecto_sis2","root","");   
         // 2 creae objeto statement
            Statement miStatement=miConexion.createStatement();
            
            String sql="SELECT codigo,nombre FROM materia WHERE usuario=?";
            
            ps=miConexion.prepareStatement(sql);
            
            ps.setString(1,usuarioo);
            rs=ps.executeQuery();
            
            ResultSetMetaData rsMd=rs.getMetaData();
            
            int cantidadColumnas=rsMd.getColumnCount();
            
            modelo.addColumn("Codigo");
            modelo.addColumn("Nombre Materia");
            
            while(rs.next()){
                   Object[] filas=new Object[cantidadColumnas];
            
                  for(int i=0;i<cantidadColumnas;i++)
                     {
                         filas[i]=rs.getObject(i+1);
                     }
                 modelo.addRow(filas);
            }
           
        }catch(SQLException e)
        {
            System.out.println("error");
        }*/
        InterfazDocente();
        holder();
        setVisible(true);
    }
    
     public void holder()
    {
        miHolder=new PlaceHolder(campoBusqueda,"nombre");
       
         
    }
    
    public void InterfazDocente()
    {
         DefaultTableModel modelo=new DefaultTableModel();
        try
        {
            
            tablaCursos.setModel(modelo);
            
            PreparedStatement ps=null;
            ResultSet rs=null;
            miConexion=DriverManager.getConnection("jdbc:mysql://localhost:3306/proyecto_sis2","root","");   
         // 2 creae objeto statement
            Statement miStatement=miConexion.createStatement();
            
            String sql="SELECT codigo,nombre,cantidadAlumnos,Aula FROM materia WHERE usuario=?";
            
            ps=miConexion.prepareStatement(sql);
            
            ps.setString(1,usuarioDocente);
            rs=ps.executeQuery();
            
            ResultSetMetaData rsMd=rs.getMetaData();
            
            int cantidadColumnas=rsMd.getColumnCount();
            
            modelo.addColumn("Codigo");
            modelo.addColumn("Nombre ");
            modelo.addColumn("Capacidad");
            modelo.addColumn("Aula");
            
            while(rs.next()){
                   Object[] filas=new Object[cantidadColumnas];
            
                  for(int i=0;i<cantidadColumnas;i++)
                     {
                         filas[i]=rs.getObject(i+1);
                     }
                 modelo.addRow(filas);
            }
           
        }catch(SQLException e)
        {
            System.out.println("error");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        eti_bienvenidaD = new javax.swing.JLabel();
        tablaPaneMisCursosl = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        eti_detalle = new javax.swing.JLabel();
        eti_codigoM = new javax.swing.JLabel();
        eti_nombreM = new javax.swing.JLabel();
        eti_cantidadAlm = new javax.swing.JLabel();
        eti_aula = new javax.swing.JLabel();
        campoCodigoM = new javax.swing.JTextField();
        campoNombreM = new javax.swing.JTextField();
        campoCantidadA = new javax.swing.JTextField();
        comboBoxAulas = new javax.swing.JComboBox();
        botonGuardar = new javax.swing.JButton();
        botonModif = new javax.swing.JButton();
        botonEliminar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaCursos = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        campoBusqueda = new javax.swing.JTextField();
        botonBuscar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaMateria = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        campoTitulo = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        textoDescripcion = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        campoRuta = new javax.swing.JTextField();
        botonEligir = new javax.swing.JButton();
        enviarPractica = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        textoForo = new javax.swing.JTextArea();
        enviarForo = new javax.swing.JButton();
        campoTamAr = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        eti_bienvenidaD.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        eti_bienvenidaD.setForeground(new java.awt.Color(240, 240, 240));
        getContentPane().add(eti_bienvenidaD, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 180, 20));

        tablaPaneMisCursosl.setBackground(new java.awt.Color(153, 255, 153));
        tablaPaneMisCursosl.setForeground(new java.awt.Color(0, 153, 153));
        tablaPaneMisCursosl.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jPanel2.setBackground(new java.awt.Color(0, 204, 153));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        eti_detalle.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        eti_detalle.setText("Detalles");
        jPanel2.add(eti_detalle, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 10, -1, -1));

        eti_codigoM.setText("Codigo:");
        jPanel2.add(eti_codigoM, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, -1, -1));

        eti_nombreM.setText("Nombre materia:");
        jPanel2.add(eti_nombreM, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        eti_cantidadAlm.setText("Cantidad alumnos:");
        jPanel2.add(eti_cantidadAlm, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, -1, -1));

        eti_aula.setText("Aula:");
        jPanel2.add(eti_aula, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, -1, -1));
        jPanel2.add(campoCodigoM, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 170, -1));

        campoNombreM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoNombreMActionPerformed(evt);
            }
        });
        jPanel2.add(campoNombreM, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 170, -1));

        campoCantidadA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoCantidadAActionPerformed(evt);
            }
        });
        jPanel2.add(campoCantidadA, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 170, -1));

        comboBoxAulas.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "selecionar", "690 A", "690 B", "690 C", "691 A", "691 B", "691 C", "691 D", "691 E", "691 F", "692 A", "692 B", "692 C", "692 D", "692 E", "692 F", "693 A", "693 B", "693 C", "693 D", "693 E", "693 F", "AUDITORIO", " " }));
        jPanel2.add(comboBoxAulas, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 170, -1));

        botonGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/guardar1.png"))); // NOI18N
        botonGuardar.setText("Guardar");
        botonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGuardarActionPerformed(evt);
            }
        });
        jPanel2.add(botonGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 110, 30));

        botonModif.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/editar1.png"))); // NOI18N
        botonModif.setText("Editar");
        botonModif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonModifActionPerformed(evt);
            }
        });
        jPanel2.add(botonModif, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 200, 110, -1));

        botonEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/eliminar2.png"))); // NOI18N
        botonEliminar.setText("Eliminar");
        botonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarActionPerformed(evt);
            }
        });
        jPanel2.add(botonEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 200, 110, -1));

        tablaCursos.setBackground(new java.awt.Color(102, 255, 204));
        tablaCursos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tablaCursos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Codigo", "Nombre Materia", "Capacidad", "Aula"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tablaCursos.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        tablaCursos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaCursosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaCursos);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 30, 460, 130));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/limpiar1.png"))); // NOI18N
        jButton3.setText("Limpiar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 200, 120, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(240, 240, 240));
        jLabel9.setText("Crear curso");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 100, -1));

        tablaPaneMisCursosl.addTab("Mis cursos", jPanel2);

        jPanel1.setBackground(new java.awt.Color(0, 204, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(240, 240, 240));
        jLabel2.setText("Lista de cursos");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, -1));
        jPanel1.add(campoBusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 140, -1));

        botonBuscar.setText("Buscar");
        botonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscarActionPerformed(evt);
            }
        });
        jPanel1.add(botonBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, -1, -1));

        tablaMateria.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Nombre"
            }
        ));
        jScrollPane2.setViewportView(tablaMateria);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 220, 170));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(240, 240, 240));
        jLabel3.setText("Subir Practica");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 10, -1, -1));

        jLabel4.setText("Titulo:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 40, -1, -1));

        jLabel5.setText("Descripcion:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 70, -1, -1));
        jPanel1.add(campoTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 40, 220, -1));

        textoDescripcion.setColumns(20);
        textoDescripcion.setRows(5);
        jScrollPane3.setViewportView(textoDescripcion);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 70, 220, 80));

        jLabel6.setText("Fecha inicio:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 160, -1, -1));

        jLabel7.setText("Fecha final:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 160, -1, -1));

        jLabel8.setText("Archivo");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 190, -1, -1));

        campoRuta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoRutaActionPerformed(evt);
            }
        });
        jPanel1.add(campoRuta, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 190, 170, -1));

        botonEligir.setText("...");
        botonEligir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEligirActionPerformed(evt);
            }
        });
        jPanel1.add(botonEligir, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 190, 50, -1));

        enviarPractica.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/enviar1.png"))); // NOI18N
        enviarPractica.setText("Enviar");
        enviarPractica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enviarPracticaActionPerformed(evt);
            }
        });
        jPanel1.add(enviarPractica, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 220, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(240, 240, 240));
        jLabel10.setText("Foro");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 10, -1, -1));

        textoForo.setColumns(20);
        textoForo.setRows(5);
        jScrollPane4.setViewportView(textoForo);

        jPanel1.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 30, 200, 180));

        enviarForo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/enviar1.png"))); // NOI18N
        enviarForo.setText("Enviar");
        enviarForo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enviarForoActionPerformed(evt);
            }
        });
        jPanel1.add(enviarForo, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 220, -1, -1));
        jPanel1.add(campoTamAr, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 190, 50, -1));

        tablaPaneMisCursosl.addTab("Actividades", jPanel1);

        jPanel3.setBackground(new java.awt.Color(0, 204, 153));
        tablaPaneMisCursosl.addTab("Practicas", jPanel3);

        getContentPane().add(tablaPaneMisCursosl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 790, 280));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/user1.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        fondo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        fondo.setForeground(new java.awt.Color(240, 240, 240));
        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/loginCopia1.jpg"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 330));
        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campoNombreMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNombreMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoNombreMActionPerformed

    private void campoCantidadAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoCantidadAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoCantidadAActionPerformed

    private void botonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGuardarActionPerformed
       
         int i=comboBoxAulas.getSelectedIndex();
        if(i>0)
        {
          insertarCursoBBDD();
        }else
        {
           JOptionPane.showMessageDialog(this,"Seleccione la Aula"); 
           return;
        }
        InterfazDocente();
        
    }//GEN-LAST:event_botonGuardarActionPerformed

    private void tablaCursosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaCursosMouseClicked
        // TODO add your handling code here:
        int seleccion=tablaCursos.getSelectedRow();
        campoCodigoM.setText(tablaCursos.getValueAt(seleccion,0)+"");
        campoNombreM.setText(tablaCursos.getValueAt(seleccion,1)+"");
        campoCantidadA.setText(tablaCursos.getValueAt(seleccion,2)+"");   
        
    }//GEN-LAST:event_tablaCursosMouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       
        limpiar();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void botonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarActionPerformed
        // TODO add your handling code here:
        eliminar();
    }//GEN-LAST:event_botonEliminarActionPerformed

    private void botonModifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonModifActionPerformed
       modificar();
    }//GEN-LAST:event_botonModifActionPerformed

    private void campoRutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoRutaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoRutaActionPerformed

    private void enviarPracticaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enviarPracticaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_enviarPracticaActionPerformed

    private void enviarForoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enviarForoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_enviarForoActionPerformed

    private void botonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscarActionPerformed
        
        String campo=campoBusqueda.getText().trim();
        
        DefaultTableModel modelo=new DefaultTableModel();
        try
        {
            
            tablaMateria.setModel(modelo);
            
            PreparedStatement ps=null;
            ResultSet rs=null;
            miConexion=DriverManager.getConnection("jdbc:mysql://localhost:3306/proyecto_sis2","root","");   
         // 2 creae objeto statement
            Statement miStatement=miConexion.createStatement();
            
            String sql="SELECT nombre FROM materia WHERE usuario=? AND nombre=?";
            
            ps=miConexion.prepareStatement(sql);
            
            ps.setString(1,usuarioDocente);
            ps.setString(2,campo);
            rs=ps.executeQuery();
            
            ResultSetMetaData rsMd=rs.getMetaData();
            
            int cantidadColumnas=rsMd.getColumnCount();
            
           
            modelo.addColumn("Nombre ");
           
            while(rs.next()){
                   Object[] filas=new Object[cantidadColumnas];
            
                  for(int i=0;i<cantidadColumnas;i++)
                     {
                         filas[i]=rs.getObject(i+1);
                     }
                 modelo.addRow(filas);
            }
           
        }catch(SQLException e)
        {
            System.out.println("error");
        }
    }//GEN-LAST:event_botonBuscarActionPerformed

    private void botonEligirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEligirActionPerformed
       
         JFileChooser buscador=new JFileChooser();
        buscador.showOpenDialog(buscador);
        try{
            String direccion=buscador.getSelectedFile().getAbsolutePath();
            campoRuta.setText(direccion);
            File fichero = new File(direccion);
            String tamArch=" "+fichero.length()+"kb";
            campoTamAr.setText(tamArch);
            FileInputStream archivo=new FileInputStream(direccion);
            DataInputStream entrada= new DataInputStream(archivo);
            
            BufferedReader buffer=new BufferedReader(new InputStreamReader(entrada));
            String lineas;
            while((lineas=buffer.readLine())!=null){
                lineas=buffer.readLine();
	        
	        System.out.println(lineas);
                
            }
            entrada.close();
        }catch(Exception e){
            
        
        }
    }//GEN-LAST:event_botonEligirActionPerformed

    public void mostrarMaterias()
    {
        
        DefaultTableModel modelo=new DefaultTableModel();
        try
        {
            
            tablaMateria.setModel(modelo);
            
            PreparedStatement ps=null;
            ResultSet rs=null;
            miConexion=DriverManager.getConnection("jdbc:mysql://localhost:3306/proyecto_sis2","root","");   
         // 2 creae objeto statement
            Statement miStatement=miConexion.createStatement();
            
            String sql="SELECT nombre FROM materia WHERE usuario=?";
            
            ps=miConexion.prepareStatement(sql);
            
            ps.setString(1,usuarioDocente);
            
            rs=ps.executeQuery();
            
            ResultSetMetaData rsMd=rs.getMetaData();
            
            int cantidadColumnas=rsMd.getColumnCount();
            
          
            modelo.addColumn("Nombre ");
           
            
            while(rs.next()){
                   Object[] filas=new Object[cantidadColumnas];
            
                  for(int i=0;i<cantidadColumnas;i++)
                     {
                         filas[i]=rs.getObject(i+1);
                     }
                 modelo.addRow(filas);
            }
           
        }catch(SQLException e)
        {
            System.out.println("error");
        }
    }
    
    public void modificar()
    {
         try {
            miConexion=DriverManager.getConnection("jdbc:mysql://localhost:3306/proyecto_sis2","root","");  
            int fila=tablaCursos.getSelectedRow();
            String codigo=tablaCursos.getValueAt(fila,0).toString();
            String sql="UPDATE materia SET nombre=?,cantidadAlumnos=? WHERE codigo=?";
            PreparedStatement miSentencia=miConexion.prepareStatement(sql);
            miSentencia.setString(1,campoNombreM.getText());
            miSentencia.setString(2,campoCantidadA.getText());
            miSentencia.setString(3,codigo);
            miSentencia.executeUpdate();
            InterfazDocente();
            limpiar();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this,"Seleccione una fila");
        }
        
    }
    public void eliminar()
    {
       
         // 2 preparar la consulta
        
        try {
            miConexion=DriverManager.getConnection("jdbc:mysql://localhost:3306/proyecto_sis2","root","");  
            int fila=tablaCursos.getSelectedRow();
            String codigo=tablaCursos.getValueAt(fila,0).toString();
            String sql="DELETE FROM materia WHERE codigo=?";
            PreparedStatement miSentencia=miConexion.prepareStatement(sql);
            miSentencia.setString(1,codigo);
            miSentencia.executeUpdate();
            InterfazDocente();
            limpiar();
        } catch (Exception ex) {
           JOptionPane.showMessageDialog(this,"Seleccione una fila");
        }
        
    }
    public void limpiar()
    {
        campoCodigoM.setText("");
        campoNombreM.setText("");
        campoCantidadA.setText("");
     
    }
    public void insertarCursoBBDD()
    {
        
         try{
         String seleccion=(String)comboBoxAulas.getSelectedItem();
         //1 Crear Conexion 
          miConexion=DriverManager.getConnection("jdbc:mysql://localhost:3306/proyecto_sis2","root","");   
         // 2 preparar la consulta
         PreparedStatement miSentencia=miConexion.prepareStatement("INSERT INTO materia (codigo,nombre,usuario,cantidadAlumnos,Aula) VALUES (?,?,?,?,?)");
         //3 establecer parametros de la consulta
          miSentencia.setString(1,campoCodigoM.getText());
          miSentencia.setString(2,campoNombreM.getText());
          miSentencia.setString(3,usuarioDocente);
          miSentencia.setString(4,campoCantidadA.getText());
          miSentencia.setString(5,seleccion);
         
          miSentencia.executeUpdate();
          JOptionPane.showMessageDialog(this,"Curso Creado");
         
        }catch(Exception error)
        {
          
            JOptionPane.showMessageDialog(this,"Llene los campos vacios");
        }
        
    }
    
    public void insetarDatosPracticaBBDD()
    {
        
        try{
        
         //1 Crear Conexion 
          miConexion=DriverManager.getConnection("jdbc:mysql://localhost:3306/proyecto_sis2","root","");   
         // 2 preparar la consulta
         PreparedStatement miSentencia=miConexion.prepareStatement("INSERT INTO practica (codPrac,Titulo, descripcion,archivoRuta, usuario) VALUES (NULL,?,?,?,?)");
         //3 establecer parametros de la consulta
          miSentencia.setString(1,campoTitulo.getText());
          miSentencia.setString(2,textoDescripcion.getText());
          miSentencia.setString(3,campoRuta.getText());
          miSentencia.setString(4,usuarioDocente);
          miSentencia.executeUpdate();
          JOptionPane.showMessageDialog(this,"Curso Creado");
         
        }catch(Exception error)
        {
          
            JOptionPane.showMessageDialog(this,"Llene los campos vacios");
        }
        
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazDocente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazDocente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazDocente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazDocente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        /*java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazDocente().setVisible(true);
            }
        });*/
        
    }
    
    public void ejecutar()
    {
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               
            }
        });
    }
    
    public String getUsuario()
    {
        return usuarioDocente;
    }
    
    
    private String usuarioDocente;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonBuscar;
    private javax.swing.JButton botonEligir;
    private javax.swing.JButton botonEliminar;
    private javax.swing.JButton botonGuardar;
    private javax.swing.JButton botonModif;
    private javax.swing.JTextField campoBusqueda;
    private javax.swing.JTextField campoCantidadA;
    private javax.swing.JTextField campoCodigoM;
    private javax.swing.JTextField campoNombreM;
    private javax.swing.JTextField campoRuta;
    private javax.swing.JTextField campoTamAr;
    private javax.swing.JTextField campoTitulo;
    private javax.swing.JComboBox comboBoxAulas;
    private javax.swing.JButton enviarForo;
    private javax.swing.JButton enviarPractica;
    private javax.swing.JLabel eti_aula;
    private javax.swing.JLabel eti_bienvenidaD;
    private javax.swing.JLabel eti_cantidadAlm;
    private javax.swing.JLabel eti_codigoM;
    private javax.swing.JLabel eti_detalle;
    private javax.swing.JLabel eti_nombreM;
    private javax.swing.JLabel fondo;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable tablaCursos;
    private javax.swing.JTable tablaMateria;
    private javax.swing.JTabbedPane tablaPaneMisCursosl;
    private javax.swing.JTextArea textoDescripcion;
    private javax.swing.JTextArea textoForo;
    // End of variables declaration//GEN-END:variables
}
